Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 29 days
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/n/home01/bcook/.conda/envs/my_home/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/n/home01/bcook/.conda/envs/my_home/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/n/home01/bcook/.conda/envs/my_home/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
  File "/n/sw/fasrcsw/apps/Core/pycuda/2015.1.3-fasrc01/lib/python2.7/site-packages/pycuda-2015.1.3-py2.7-linux-x86_64.egg/pycuda/gpuarray.py", line 951, in to_gpu
    result = GPUArray(ary.shape, ary.dtype, allocator, strides=_compact_strides(ary))
  File "/n/sw/fasrcsw/apps/Core/pycuda/2015.1.3-fasrc01/lib/python2.7/site-packages/pycuda-2015.1.3-py2.7-linux-x86_64.egg/pycuda/gpuarray.py", line 202, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
LogicError: ('cuMemAlloc failed: invalid device context', <function to_gpu at 0x2b16e43fe410>, (array([ 1.8710494], dtype=float32),))

slurmstepd: error: *** JOB 85559512 ON supermicgpu01 CANCELLED AT 2017-04-11T11:53:18 DUE TO TIME LIMIT ***
